---
title: "method_validation"
author: "Camille Crapart"
date: '2022-09-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, cache = F, collapse = T,  message = F, warning = F, error = F)
```

```{r libraries}
library(ggplot2)
library(cowplot)
library(dplyr)
library(readxl)
library(lme4)


memory.limit(size = 1e+10)

id.names <- c("station_id","station_code","nve_vatn_nr","nve_vassdrag_nr", "CBA_Lake_ID", "STATION_ID", "statn_d","longitude","latitude", "region", "region2")
is_constant <- function(x) length(unique(x)) == 1L 
```


# Intro

Questions: 

* Is the incubation method reliable?

* What experimental factors influence most the results?


# Full dataset

Create a dataset merging respiration rates for the 1000 and the 100 lakes, together with water chemistry and catchments predictors.

## Merge respiration rates from 1000 and 100 lakes

```{r merged.rr, eval = F}
allsamples <- read.csv("All_samples.csv")
rrtotal <- read.csv("RRtotal.csv")

merged.rr <- merge(allsamples, rrtotal, by = c("Sample_ID", "Survey"))

merged.rr$X <- NULL
merged.rr$line <- NULL

newdate <- paste("20",substr(merged.rr$Start_date,1,2),"/",substr(merged.rr$Start_date,3,4),"/",substr(merged.rr$Start_date,5,6), sep = "")
merged.rr$exp.date <- as.Date(newdate)

write.csv(merged.rr, "merged.rr.csv")
```

```{r merge-niva-data, eval = F}

merged.rr <- read.csv("merged.rr.csv")

bdg.niva <- readRDS("bdg.niva.rds") %>% 
  dplyr::select(c("STATION_ID","CBA_Lake_ID","LAKE_NAME","SAMPLED_DATE","longitd","latitud","lake_area_km2","basin_area_km2","mar_limit","mean_elev","developed","agriculture","forest","natural_not_forest","peat","glacier","freshwater","sea","era_prec_2019","nilu_ndep_2012_2016","nilu_sdep_2012_2016","Dyp","rr_2m_19","tg_2m_19","doc_c_2019","kond_2019","toc_2019","ph_2019","tn_2019","tp_2019","region2","geometry")) 

waterchem <- read_xlsx("waterchem.xlsx") %>% 
  dplyr::select(c("Sample_ID","date","lat","long","DOC","TOC","cond_µS.m","pH","TN","TP")) %>%
  setNames(c("Sample_ID","SAMPLED_DATE","latitud","longitd","doc_c_2019","toc_2019","kond_2019","ph_2019","tn_2019","tp_2019")) %>%
  as.data.frame()# 100 lakes

rrniva <- merge(merged.rr, bdg.niva, by.x = "Sample_ID", by.y = "CBA_Lake_ID")
rrcba <- rrniva %>% filter(Survey == "100_lakes") %>% merge(waterchem, by = "Sample_ID")

remove <- grep("\\.x",names(rrcba))
rrcba <- rrcba[,-remove]
rename <- gsub("\\.y",x = names(rrcba), replacement = "")
names(rrcba) <- rename

rr_comp <- rbind(filter(rrniva, Survey == "1000_lakes"),rrcba)
rr_comp$SAMPLED_DATE <- as.Date(rr_comp$SAMPLED_DATE)
rr_comp$exp.date <- as.Date(rr_comp$exp.date)

rr_comp$diff.date <- rr_comp$exp.date - rr_comp$SAMPLED_DATE
rr_comp$diff.week <- difftime(rr_comp$exp.date, rr_comp$SAMPLED_DATE, units = "weeks") %>% round(digits = 0)

rr_comp$com <- NA
index_nocom <- which(rr_comp$Comments == "")
rr_comp$com[index_nocom] <- "nocom"
rr_comp$com[which(is.na(rr_comp$com))] <- "com"

saveRDS(rr_comp,"rr_comp.rds")
```

```{r 1000L-vs-100L}
rr_comp <- readRDS("rr_comp.rds")
common_id <- filter(rr_comp, Survey == "100_lakes") %>% pull("Sample_ID")
  
q1 <- qplot(x = filter(rr_comp, Sample_ID %in% common_id & Survey == "100_lakes")$dmax, y = filter(rr_comp, Sample_ID %in% common_id & Survey == "1000_lakes")$dmax, colour = as.factor(filter(rr_comp, Sample_ID %in% common_id& Survey == "1000_lakes")$diff.date))+
  labs(x="RR 100 lakes", y = "RR 1000 lakes", col = "Days between sampling and incubation")+
  scale_color_viridis_d()+
  theme_minimal()

q2 <- qplot(x = filter(rr_comp, Sample_ID %in% common_id & Survey == "100_lakes")$hwidth, y = filter(rr_comp, Sample_ID %in% common_id & Survey == "1000_lakes")$hwidth, colour = as.factor(filter(rr_comp, Sample_ID %in% common_id& Survey == "1000_lakes")$diff.date))+
  labs(x="BdgT 100 lakes", y = "BdgT 1000 lakes", col = "Days between sampling and incubation")+
  scale_color_viridis_d()+
  theme_minimal()

library(ggpubr)

ggarrange(q1,q2,common.legend = T, ncol = 2)
```

```{r fit-dmax}
ggplot(rr_comp)+geom_point(aes(x=fit_r2, y = dmax))+xlim(0.99,1)

boxplot(rr_comp$fit_r2)


````

## Scale variables

```{r sort-df, eval = F}

rr_comp <- readRDS("rr_comp.rds")

rrcompsc <- subset(rr_comp, fit_r2 > 0.6) %>% subset(hwidth > 0)
#rrcompsc <- subset(rr_comp, log(dmax)> 0) %>% subset(log(hwidth)> 0)
rrcompsc$logdmaxsc <- rrcompsc$dmax %>% log() %>% scale() %>% as.numeric()
rrcompsc$loghwidthsc <- rrcompsc$hwidth %>% log() %>% scale() %>% as.numeric()
rrcompsc$logtocsc <- rrcompsc$toc_2019 %>% log() %>% scale() %>% as.numeric()

saveRDS(rrcompsc, "rrcompsc.rds")
```

```{r plot-rr, fig.dim = c(20,20)}
rrcompsc <- readRDS("rrcompsc.rds")

g1 <- ggplot(rrcompsc)+geom_line(aes(y=latitud, x = logdmaxsc, col = as.factor(diff.date), group = Sample_ID))+
  labs(y = "Latitude", x = "RR, log and scaled", col = "Days between sampling and incubation")+
  scale_color_viridis_d()+
  facet_grid(cols = vars(Survey))+
  theme(legend.position = "none")+
  theme_minimal(base_size = 30)

g2 <- ggplot(rrcompsc)+geom_line(aes(y=latitud, x = loghwidthsc, col = as.factor(diff.date), group = Sample_ID))+
  labs(y = "Latitude", x = "BdgT, log and scaled", col = "Days between sampling and incubation")+
  scale_color_viridis_d()+
  facet_grid(cols = vars(Survey))+
  theme(legend.position = "none")+
  theme_minimal(base_size = 30)

ggarrange(g1,g2,common.legend = T, nrow = 2)

```


## Plot

```{r plot-diff, fig.dim = c(10,5)}
rrcompsc <- readRDS("rrcompsc.rds")

ggplot(rrcompsc)+geom_point(aes(x=loghwidthsc, y = logdmaxsc, col = Survey))+
  facet_grid(cols=vars(region2))+
    theme_minimal()+
  theme(legend.position = "bottom")


```








```{r mixed-model-date, fig.dim = c(20,10)}
s0 <- summary(lme0  <- lmer(logdmaxsc ~ 1 + (1 | region2/Sample_ID) + (1 | diff.week) + (1 | com), data=rrcompsc))
data.frame(variance = s0$varcor) %>% knitr::kable()

library(sjPlot)
library(glmmTMB)
plot_model(lme0, type = "re")[[1]]

```


## Study standard deviation of measurements

```{r sd-sample}
rrcompsc <- readRDS("rrcompsc.rds")
rrsum <- rrcompsc %>% group_by(Sample_ID,Survey) %>% summarize(rr_mean = mean(dmax), rr_sd = sd(dmax), rr_median = median(dmax), bdgt_mean = mean(hwidth), bdgt_sd = sd(hwidth), bdgt_median = median(hwidth))
saveRDS(rrsum, "rrsum.rds")

remove_columns <- c(names(merged.rr)[-which(names(merged.rr) %in% c("Sample_ID","Survey", "Who","Sampling_date","exp.date"))], "logdmaxsc", "loghwidthsc")

d <- distinct(select(rrcompsc, !all_of(remove_columns)))
rrcompsum <- merge(rrsum, d, by = c("Sample_ID", "Survey"), all.y = F)

rrcompsum$logrrsdsc <- rrcompsum$rr_sd %>% log %>% scale %>% as.numeric
rrcompsum$logbdgtsdsc <- rrcompsum$bdgt_sd %>% log %>% scale %>% as.numeric

summary(lme2  <- lmer(logrrsdsc ~ 1 + (1 | region2) + (1 | Who), data=rrcompsum))
summary(lme2b  <- lmer(logbdgtsdsc ~ 1 + (1 | region2) + (1 | Who), data=rrcompsum))
summary(lme2c  <- lmer(rr_sd ~ 1 + (1 | region2) + (1 | Who) + (1 | com) + (1 | diff.week), data=rrcompsum))
plot_model(lme2c, type = "re")

ggplot(rrcompsum)+geom_point(aes(y = rr_sd, x = rr_mean))

saveRDS(rrcompsum, "rrcompsum.rds")
```

```{r plot-sample-dmax, fig.dim = c(20,10)}
ggplot(rrcompsum, aes(x=as.factor(Sample_ID), y = rr_mean, col = Survey))+geom_point()+
  geom_errorbar(aes(ymin =rr_mean - rr_sd, ymax = rr_mean + rr_sd))+
  labs(x = "Sample ID", y = "RR, log and scaled")+theme_minimal(base_size = 30)

ggplot(rrcompsum, aes(x=as.factor(Sample_ID), y = bdgt_mean, col = Survey))+geom_point()+
  geom_errorbar(aes(ymin =bdgt_mean - bdgt_sd, ymax = bdgt_mean + bdgt_sd))+
  labs(x = "Sample ID", y = "BdgT, log and scaled")+theme_minimal(base_size = 30)
```

```{r plot-sd, fig.dim = c(20, 10)}
ggplot(rrcompsum, aes(x = rr_mean, y = latitud, col = Survey))+
  geom_point()+geom_errorbar(aes(xmin = rr_mean - rr_sd, xmax = rr_mean + rr_sd))+
  labs(y = "Latitude", y = "RR, log and scaled")+theme_minimal(base_size = 30)

ggplot(rrcompsum, aes(x = bdgt_mean, y = latitud, col = Survey))+
  geom_point()+geom_errorbar(aes(xmin = bdgt_mean - bdgt_sd, xmax = bdgt_mean + bdgt_sd))+
  labs(y = "Latitude", y = "BdgT, log and scaled")+theme_minimal(base_size = 30)
```



```{r remove-high-variability}
rrcompr <- filter(rrcompsum, rr_sd < 5)

rrcompr$logrrsc <- rrcompr$rr_mean %>% log %>% scale
rrcompr$logbdgtsc <- rrcompr$bdgt_mean %>% log %>% scale

saveRDS(rrcompr, "rrcompr.rds")
```

```{r plots-low-var}
rrcompr <- readRDS ("rrcompr.rds")

rrcompru <- rrcompr[!duplicated(rrcompr$Sample_ID),]

summary(lm1  <- lm(logrrsc ~ logtocsc + region2, data=rrcompr))
summary(lme1  <- lmer(logrrsc ~ logtocsc + (logtocsc | region2) + (logtocsc | Who), data=rrcompr))
summary(lme1b  <- lmer(logrrsc ~ logtocsc + (1 | region2) + (1 | Who), data=rrcompr))


aov(logrrsc~region2, data = group_by(rrcompr, Sample_ID))

ggplot(group_by(rrcompr, Sample_ID),aes(x = region2, y=logrrsc))+geom_boxplot(outlier.shape = NA, notch = T)+
  geom_jitter(aes(col=region2))+ labs(x = "", y = "log.rr.sc", col = "Region", title = "log.rr.sc for samples with sd < 5")+
  theme_minimal(base_size = 25)

ggplot(rrcompr,aes(x = region2, y=logbdgtsc))+geom_boxplot(outlier.shape = NA, notch = T)+
  geom_jitter(aes(col=region2))+ labs(x = "", y = "log.bdgt.sc", col = "Region", title = "log.bdgt.sc for samples with rr.sd < 5")+
  theme_minimal(base_size = 25)

ggplot(rrcompr)+geom_point(aes(x=rr_mean, y = rr_median))
ggplot(rrcompsum)+geom_point(aes(x=rr_mean, y = rr_median))


```

```{r epxlore-high-variability}
rrcompr2 <- filter(rrcompsum, rr_sd > 5)

rrcompr2$logrrsc <- rrcompr2$rr_mean %>% log %>% scale
rrcompr2$logbdgtsc <- rrcompr2$bdgt_mean %>% log %>% scale
rrcompr2$logrrsdsc <- rrcompr2$rr_sd %>% log %>% scale

saveRDS(rrcompr2, "rrcompr2.rds")

summary(lm3  <- lm(logrrsc ~ logtocsc + region2, data=rrcompr2))
summary(lme3  <- lmer(logrrsc ~ logtocsc + (1 | region2) + (1 | Who), data=rrcompr2))

aov(logrrsc~region2, data = rrcompr)

ggplot(rrcompr,aes(x = region2, y=logrrsc))+geom_boxplot(outlier.shape = NA, notch = T)+
  geom_jitter(aes(col=region2))+ labs(x = "", y = "log.rr.sc", col = "Region")+
  theme_minimal(base_size = 25)

ggplot(rrcompr,aes(x = region2, y=logbdgtsc))+geom_boxplot(outlier.shape = NA, notch = T)+
  geom_jitter(aes(col=region2))+ labs(x = "", y = "log.bdgt.sc", col = "Region")+
  theme_minimal(base_size = 25)

ggplot(rrcompr)+geom_point(aes(x=rr_mean, y = rr_median))
ggplot(rrcompsum)+geom_point(aes(x=rr_mean, y = rr_median))

```